### ISSUE TITLE
Preview Error - Standalone launcher - AdaptLearning Authoring Tool

### ISSUE THREAD

**Issue by Rajesh-08** [fabiobeoni/adapt-authoring-standalone#4]
I have download and run the Adapt Standalone launcher, its working perfectly.

Have created the new course and saved it. While clicking the preview button on left it show the "Error generating preview, please contact Administrator."

Also attached the screenshot below.

Kindly do your needful.

![unnamed](https://user-images.githubusercontent.com/43462434/45865154-31a04380-bd9a-11e8-91dd-9250a4895678.png)

**Comment by fabiobeoni** [comment]
Hi,

It's a known issue of the AT. You may get it because there is an empty component in your course, or something else not working properly into the course.

I would suggest you to undo the last couple of changes you have done while creating your lesson page (article, row, component) to see if then you can preview the course.

If you can't, then please try previewing a new course with a single lesson and a sample text box into it.

Then let me know how it goes.

**Comment by Rajesh-08** [comment]
> Hi,
> 
> It's a known issue of the AT. You may get it because there is an empty component in your course, or something else not working properly into the course.
> 
> I would suggest you to undo the last couple of changes you have done while creating your lesson page (article, row, component) to see if then you can preview the course.
> 
> If you can't, then please try previewing a new course with a single lesson and a sample text box into it.
> 
> Then let me know how it goes.

Hi, 

Thanks for the quick turn around!

I have create the new course with sample text box into it. 

It throwing the same error.

**Comment by fabiobeoni** [comment]
Could you please attach the application logs?

**Comment by fabiobeoni** [comment]
Hello @Rajesh-08 , I am closing this issue since without more information I cannot replicate it.
